name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          sudo apt install -y google-chrome-stable xvfb
          seleniumbase install chromedriver

      - name: Run with Xvfb
        run: |
          xvfb-run python run.py

      - name: Upload Screenshots as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./screenshot_example1.png  # Ganti dengan path screenshot yang relevan
