name: Run SeleniumBase Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:

    env:
      PY_COLORS: "1"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          sudo apt install -y google-chrome-stable
          seleniumbase install chromedriver
          sudo apt install -y xvfb
          export DISPLAY=:0
          /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
          sleep 5

      - name: Run SeleniumBase Script
        run: |
           xvfb-run python run.py --browser=chrome --headless
