name: Run SeleniumBase Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:

    env:
      PY_COLORS: "1"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          pip install -r requirements.txt

      - name: Install SeleniumBase
        run: |
          pip install seleniumbase

      - name: Install ChromeDriver
        run: |
          seleniumbase install chromedriver

      - name: Verify pytest
        run: |
          echo "def test_sample(): pass" > sample_test.py
          pytest sample_test.py

      - name: Run SeleniumBase Script
        run: |
          python run.py --browser=chrome --headless
